### ISSUE TITLE
 ROUTER/DEALER pattern?

### ISSUE THREAD

**Issue by ghost** [ellisonbg/zmqweb#4]
Hi Brian

I am just getting started with zmq and I already think I wish zmqweb would work different. A slow or locked backend will kill zmqwebs performance and the frontend keeps sending errors to users. My idea:

frontend - ROUTER
backend - DEALER

Each backend sends the frontend N tokens (msg_ids). The frontend then sends the web-requests by replying to the tokens. The reply from the backend is a new token for the frontend. If a backend is slow, the frontend will run out of tokens from that backend and therefore ignore it, until the tokens return from the backend.

If the frontend runs out of tokens (globally) the web-requests are queued. The recv handler on the frontend then will use tokens immediately instead of storing them.

That way if a backend locks the users will see max N errors.

If I continue to be that obsessed with zmq, you probably get a pull request soon. :-)

Jean-Louis

Edit: I just learned that only DEALER is async. And there is a picture: 

![Picture](https://github.com/imatix/zguide/raw/master/images/fig37.png)

**Comment by ellisonbg** [comment]
Glad you are having fun with thinking about these things.  I agree it is fun :)

I think your idea has potential.  Right now, these backend failures are handled using timeouts.  If a backend hasn't replied after timeout milliseconds, the frontend sends a 504 error to the client.

The problem with your approach is that if a backend dies while it is working on a request, there is no error handling.  Or were you thinking of still having timeouts.

The other general experience I have in using ZeroMQ, is that if you ever find yourself in the situation where you have to maintain your own application level queue, you are probably doing things wrong.  That is what ZMQ is best all - queueing things.

But, there is definitely room for zmqweb to improve in this area.  Maybe a hybrid approach might work.  But what specific usage case are you trying to solve?  Rescheduling backend tasks is a backend is slow?  Backend failures?  etc/

**Comment by ghost** [comment]
> Glad you are having fun with thinking about these things. I agree it is fun :)

I love solutions that come naturally by changing the representation of the problem. ZMQ does that.

> I think your idea has potential. Right now, these backend failures are handled using timeouts. If a backend hasn't replied after timeout milliseconds, the frontend sends a 504 error to the client.
> 
> The problem with your approach is that if a backend dies while it is working on a request, there is no error handling. Or were you thinking of still having timeouts.

There should be timeouts. It would be implemented the same way it already is (DelayedCallback). Of course when the reply finally arrives after the timeout, it is still considered a token.

> The other general experience I have in using ZeroMQ, is that if you ever find yourself in the situation where you have to maintain your own application level queue, you are probably doing things wrong. That is what ZMQ is best all - queueing things.

I realized you don't have to queue anything. The incoming tokens/replies are queued by zmq. When the fronted runs out of tokens (queued by zmq) its probably wise not to accept any further connections, there is no benefit in accepting them since they can't be handled anyways. Some backlog will be handled by the OS. So we can get rid of all the queueing.

> But, there is definitely room for zmqweb to improve in this area. Maybe a hybrid approach might work. But what specific usage case are you trying to solve? Rescheduling backend tasks is a backend is slow?  Backend failures? etc/

Well, I'd call it "natural"-load-balancing. I think some load-balancing methods are stupid: agents that measure CPU usage or load, these are just symptoms, often even unrelated. If you load-balance by backlog it makes much more sense: a slow backend will build-up backlog and if you only have a certain window (N tokens) the flow will be controlled naturally. Actually its a bit like tcp works and it has a statistical aspect: There are more tokens of fast backends ready, so load gets distributed (evened?) before the window closes. Of course there is not only fast/slow but also small/large problems for the backend. Backend failures are handled for free.

With DEALER/ROUTER under almost full load the backend on the machine with a significant worse performance would buildup a backlog that will cause 504 while there are still machines that could handle the request.

I plan to use zmqweb with blocking IO. Say I have this SQL-API with no async interface. And sometimes there is a bad SQL query. There are two backends. UserA blocks backendA and userB is doing several requests. UserB will get: 200, 504, 200, 504, 200…. On the other hand if we have ROUTER/DEALER with two tokens each backend userB will get: 200, 504, 200, 200, 200, 200…

I admit that current DEALER/ROUTER pattern is perfect for problems tornado is meant for, but zmqweb is a nice container for other kinds of applications and would open the door for lightweight and sane worker based concurrency for a framework like django.

**Comment by ghost** [comment]
A hybrid approach that allows bidirectional streaming would be perfect. If I understood the code right: A large upload would use its size RAM on front- and backend, while downloads can be streamed. With ROUTER/DEALER bidirectional streaming should IMO work.

**Comment by ghost** [comment]
I learned that tornado always puts the whole body into a request, this might be a hint, that my idea violates tornados purpose.

**Comment by ellisonbg** [comment]
Getting back to this again.  BTW, will you be at PyCon next week by and chance?  If so, we should sit down at chat some.

One of the big questions I have had in thinking about zmqweb lately is what advantage zmqweb provides over a low-level http proxy like nginx or haproxy, which both do load balancing.  Here are some thoughts about that..
- Bare proxies don't provide any additional error handling.  If a backend HTTP server gets slow, the proxy will keep sending it requests.
- Not very dynamic.  While you can add and remove backends from a proxy at runtime, the ZMQ architecture opens up the door for a much more dynamic approach where backend handlers come and go
- zmqweb makes it really easy to scale single operations that are slow or blocking (like db calls).

With these things in mind, I would say my goal for zmqweb is to focus on the scalability and error handling.  If we can kill that well, I think we have something that raw HTTP proxies don't have.  So what are the main types of errors we want to be able to handle?
- A backend goes away while handling a request.  In this case, the request should time out and automatically be send to a different backend.  The problem is that if the backend has any additional tokens in the frontend, the frontend will keep sending requests to it for a few.
- A backend is just really slow.  In this case, a different backend should be tried as well.

On the scalability side, I think we want to make sure that things behave in a sane way as backends come and go.

One other question - the current design allows backends to connect to multiple frontends - that is nice when you need both sides to scale.  

If you think the token idea could help with these things, let's pursue that.  Can you start a wiki page with an outline of the main design points?  We can then iterate on the design there.  Cheers, Brian

**Comment by ghost** [comment]
I did a comparison of zmqweb and nginx+uwsgi. nginx+uwsgi is the closest to zmqweb I found, it runs a informed protocol and therefore allows error handling. I was quite surprised:
- nginx+uwsgi seems to assign failed requests (due timeout and dying backends) to another backend. I wasn't able to produce any failures as long as there are working backends
- nginx has a feature called [least_conn](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#least_conn) it behaves a bit like my token idea: Backends with a large backlog will get less requests. This feature is the first solution to that slow-backend-problem I am aware of. Requests per second will drop only by about 50% with this feature enabled.
- uwsgi's loadbalancing performs as bad as nginx+uwsgi without least_conn or zmqweb.
- but both will not report any failure back to the client, which zmqweb currently does.

What did I test:
- 5 Backends that react in 20ms
- 1 Backend that reacts in 1s
- Run the test twice with and without slow-backend

As usual the test procedure has a flaw:

``` bash
ab -n 10000 -c 100 http://harry:8080/
```

This will test with 100 concurrent connections. When the test runs the slow-backend will soon bind all 100 sockets and almost no requests go to the fast backends. Thats a bit more extreme than it would happen in reality, where the slow backend still would gather connections:
- In zmqweb: ~~within the 2 second timeout frame~~ actually its boundless or bounded by queue/memory size
- In nginx+uwsgi/uwsgi till socket backlog is used up with is by default 100

So at the moment zmqweb scores because of the simple design and simple deployment and not yet because of error handling.

> One other question - the current design allows backends to connect to multiple frontends - that is nice when you need both sides to scale.

Maybe n-to-n routing would help which means it would need a dedicated router.
- zmqweb parses the requests in the frontend so with sufficient backends the frontend can become the bottleneck
- of course then the router is the next bottleneck

I am a bit torn, I like zmqweb because of the simplicity and like to keep it that way, but to address the problems complexity must be added. And ATM for the needs at work nginx+uwsgi and tornado for ajax will win.

For example:

> The problem is that if the backend has any additional tokens in the frontend, the frontend will keep sending requests to it for a few.

One could add logic: not to retry a backend after timeout until one token returns. such things kill the beauty of the design.

The other big question is: If we lose simplicity anyway wouldn't it be better to directly use zmq as a middleware without forwarding http-requests? You can use zmq to decouple\* blocking tasks directly in tornado. If you move all high CPU and blocking tasks to decoupled backends tornado can shine with its async capabilities. Maybe a tornado-async-task-decoupling-framework is a better goal?

*\* I can't think of any better word ATM.

My thoughts mostly source from the slow-backend problem I experienced: in practice I solved it by routing the potentially slow handlers to a independent backend pool. So maybe this problem should always be solved as the case arises. Which means for zmqweb: error handling should be improved, it already allows to easily define independent backend pools and ROUTER/DEALER isn't needed.

Maybe we can continue the discussion a bit.. before defining design points. I usually have many ideas but structuring those takes more time/effort.

**Comment by ellisonbg** [comment]
On Fri, Mar 8, 2013 at 4:03 PM, Jean-Louis Fuchs
notifications@github.comwrote:

> I did a comparison of zmqweb and nginx+uwsgi. nginx+uwsgi is the closest
> to zmqweb I found, it runs a informed protocol and therefore allows error
> handling. I was quite surprised:
> - nginx+uwsgi seems to assign failed requests (due timeout and dying
>   backends) to another backend. I wasn't able to produce any failures as long
>   as there are working backends
> - nginx has a feature called least_connhttp://nginx.org/en/docs/http/ngx_http_upstream_module.html#least_connit behaves a bit like my token idea: Backends with a large backlog will get
>   less requests. This feature is the first solution to that
>   slow-backend-problem I am aware of. Requests per second will drop only by
>   about 50% with this feature enabled.
> - uwsgi's loadbalancing performs as bad as nginx+uwsgi without
>   least_conn or zmqweb.
> - but both will not report any failure back to the client, which
>   zmqweb currently does.
> 
> What did I test:
> - 5 Backends that react in 20ms
> - 1 Backend that reacts in 1s
> - Run the test twice with and without slow-backend
> 
> As usual the test procedure has a flaw:
> 
> ab -n 10000 -c 100 http://harry:8080/
> 
> This will test with 100 concurrent connections. When the test runs the
> slow-backend will soon bind all 100 sockets and almost no requests go to
> the fast backends. Thats a bit more extreme than it would happen in
> reality, where the slow backend still would gather connections:
> - In zmqweb: within the 2 second timeout frame
> - In nginx+uwsgi/uwsgi till socket backlog is used up with is by
>   default 100
> 
> So at the moment zmqweb scores because of the simple design and simple
> deployment and not yet because of error handling.
> 
> This is great that you tested this stuff out.  I wasn't aware of how
> nginx+uwsgi worked in this respect.

The other way that zmqweb scores for us is that we are building everything
on zmq+tornado - not nginx or uwsgi.  But you are right

> Maybe n-to-n routing would help which means it would need a dedicated
> router.
> - zmqweb parses the requests in the frontend so with sufficient
>   backends the frontend can become the bottleneck
> - of course then the router is the next bottleneck
> 
> I am a bit torn, I like zmqweb because of the simplicity and like to keep
> it that way, but to address the problems complexity must be added. And ATM
> for the needs at work nginx+uwsgi and tornado for ajax will win.
> 
> Yes, zmqweb does have additional complexity in how it parses requests in
> the frontend and stuffs everything into non-http serialization.  I am turn
> as well.  Maybe a bit of history will help explain why I wrote zmqweb.
>  Originally, I had all of my handlers in the frontend.  Eventually that
> became a problem because of blocking handlers, etc..  But I already had the
> handlers written so I wanted a simple way of running handlers in a
> different process.  This was sort of inspired by mongrel2.  The benefit is
> that the handlers don't have to change one bit.  That is some simplicity
> that I would like to keep - being able to write handlers in the frontend
> first and then move them to scalable backends as needed.
> 
> For example:
> 
> The problem is that if the backend has any additional tokens in the
> frontend, the frontend will keep sending requests to it for a few.
> 
> One could add logic: not to retry a backend after timeout until one token
> returns. such things kill the beauty of the design.
> 
> The other big question is: If we lose simplicity anyway wouldn't it be
> better to directly use zmq as a middleware without forwarding
> http-requests? You can use zmq to decouple\* blocking tasks directly in
> tornado. If you move all high CPU and blocking tasks to decoupled backends
> tornado can shine with its async capabilities. Maybe a
> tornado-async-task-decoupling-framework is a better goal?
> 
> FWIW, I wrote a simple RPC layer for ZMQ for that usage case as well
> (tornado-async-task-decoupling-framework).  We are currently using both of
> these in our web apps.  But right now, zpyrpc has all of the same problems
> as zmqweb - it uses the same logic for timeouts, and error handling.  It
> could be improved, but at the cost of complexity.  zmqweb and zpyrpc sort
> of solve the same problem and have the same limitations - the main
> difference is the wire protocol and the form the backend code takes.

I guess there are two questions:
- What type of code we want to have to write?  Just HTTP request handlers?
  Or HTTP request handlers that talk zpyrpc to a non HTTP backend.
- How far do we want to go with error handling and scalability.

I would love to have something that does a better job of error handling and
scalability (we will need that) but I realize the complexity comes with a
cost.

> *\* I can't think of any better word ATM.
> 
> My thoughts mostly source from the slow-backend problem I experienced: in
> practice I solved it by routing the potentially slow handlers to a
> independent backend pool. So maybe this problem should always be solved as
> the case arises. Which means for zmqweb: error handling should be improved,
> it already allows to easily define independent backend pools and
> ROUTER/DEALER isn't needed.
> 
> Maybe we can continue the discussion a bit.. before defining design
> points. I usually have many ideas but structuring those takes more
> time/effort.
> 
> Yes, let's keep discussing+thinking about these things.  Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ellisonbg/zmqweb/issues/4#issuecomment-14653299
> .

## 

Brian E. Granger
Cal Poly State University, San Luis Obispo
bgranger@calpoly.edu and ellisonbg@gmail.com
